
from abc import ABC
class Visitor(ABC):

  def visit_Expression(self, expression):
    pass

  def visit_Assignment(self, assignment):
    pass

  def visit_Binary(self, binary):
    pass

  def visit_Unary(self, unary):
    pass

  def visit_Literal(self, literal):
    pass

  def visit_Grouping(self, grouping):
    pass

  def visit_Variable(self, variable):
    pass

  def visit_Logical(self, logical):
    pass

  def visit_Call(self, call):
    pass

# GENERATED BY syntax.py
class Expression:
  def __init__(self, expr):
    self.expr = expr


  def accept(self, visitor):
    pass


# GENERATED BY syntax.py
class Assignment(Expression):
  def __init__(self, name, value):
    super().__init__(self)
    self.name = name
    self.value = value


  def accept(self, visitor):
    return visitor.visit_Assignment(self)


# GENERATED BY syntax.py
class Binary(Expression):
  def __init__(self, left_expr, op, right_expr):
    super().__init__(self)
    self.left_expr = left_expr
    self.op = op
    self.right_expr = right_expr


  def accept(self, visitor):
    return visitor.visit_Binary(self)


# GENERATED BY syntax.py
class Unary(Expression):
  def __init__(self, op, expr):
    super().__init__(self)
    self.op = op
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_Unary(self)


# GENERATED BY syntax.py
class Literal(Expression):
  def __init__(self, token):
    super().__init__(self)
    self.token = token


  def accept(self, visitor):
    return visitor.visit_Literal(self)


# GENERATED BY syntax.py
class Grouping(Expression):
  def __init__(self, expr):
    super().__init__(self)
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_Grouping(self)


# GENERATED BY syntax.py
class Variable(Expression):
  def __init__(self, name):
    super().__init__(self)
    self.name = name


  def accept(self, visitor):
    return visitor.visit_Variable(self)


# GENERATED BY syntax.py
class Logical(Expression):
  def __init__(self, left_expr, op, right_expr):
    super().__init__(self)
    self.left_expr = left_expr
    self.op = op
    self.right_expr = right_expr


  def accept(self, visitor):
    return visitor.visit_Logical(self)


# GENERATED BY syntax.py
class Call(Expression):
  def __init__(self, callee, closing_paren, arguments):
    super().__init__(self)
    self.callee = callee
    self.closing_paren = closing_paren
    self.arguments = arguments


  def accept(self, visitor):
    return visitor.visit_Call(self)

