
from abc import ABC
class Visitor(ABC):

  def visit_Expression(self, expression):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Expression from Expression")

  def visit_Assignment(self, assignment):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Assignment from Expression")

  def visit_Binary(self, binary):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Binary from Expression")

  def visit_Unary(self, unary):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Unary from Expression")

  def visit_Literal(self, literal):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Literal from Expression")

  def visit_Grouping(self, grouping):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Grouping from Expression")

  def visit_Variable(self, variable):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Variable from Expression")

  def visit_Logical(self, logical):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Logical from Expression")

  def visit_Call(self, call):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Call from Expression")

  def visit_Get(self, get):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Get from Expression")

  def visit_Set(self, set):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR Set from Expression")

  def visit_This(self, this):
    raise RuntimeError("DIDNT IMPLEMENT VISIT FOR This from Expression")

# GENERATED BY syntax.py
class Expression:
  def __init__(self, expr):
    self.expr = expr


  def accept(self, visitor):
    pass


# GENERATED BY syntax.py
class Assignment(Expression):
  def __init__(self, name, value):
    super().__init__(self)
    self.name = name
    self.value = value


  def accept(self, visitor):
    return visitor.visit_Assignment(self)


# GENERATED BY syntax.py
class Binary(Expression):
  def __init__(self, left_expr, op, right_expr):
    super().__init__(self)
    self.left_expr = left_expr
    self.op = op
    self.right_expr = right_expr


  def accept(self, visitor):
    return visitor.visit_Binary(self)


# GENERATED BY syntax.py
class Unary(Expression):
  def __init__(self, op, expr):
    super().__init__(self)
    self.op = op
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_Unary(self)


# GENERATED BY syntax.py
class Literal(Expression):
  def __init__(self, token):
    super().__init__(self)
    self.token = token


  def accept(self, visitor):
    return visitor.visit_Literal(self)


# GENERATED BY syntax.py
class Grouping(Expression):
  def __init__(self, expr):
    super().__init__(self)
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_Grouping(self)


# GENERATED BY syntax.py
class Variable(Expression):
  def __init__(self, name):
    super().__init__(self)
    self.name = name


  def accept(self, visitor):
    return visitor.visit_Variable(self)


# GENERATED BY syntax.py
class Logical(Expression):
  def __init__(self, left_expr, op, right_expr):
    super().__init__(self)
    self.left_expr = left_expr
    self.op = op
    self.right_expr = right_expr


  def accept(self, visitor):
    return visitor.visit_Logical(self)


# GENERATED BY syntax.py
class Call(Expression):
  def __init__(self, callee, closing_paren, arguments):
    super().__init__(self)
    self.callee = callee
    self.closing_paren = closing_paren
    self.arguments = arguments


  def accept(self, visitor):
    return visitor.visit_Call(self)


# GENERATED BY syntax.py
class Get(Expression):
  def __init__(self, name, object):
    super().__init__(self)
    self.name = name
    self.object = object


  def accept(self, visitor):
    return visitor.visit_Get(self)


# GENERATED BY syntax.py
class Set(Expression):
  def __init__(self, object, name, value):
    super().__init__(self)
    self.object = object
    self.name = name
    self.value = value


  def accept(self, visitor):
    return visitor.visit_Set(self)


# GENERATED BY syntax.py
class This(Expression):
  def __init__(self, token):
    super().__init__(self)
    self.token = token


  def accept(self, visitor):
    return visitor.visit_This(self)

