
from abc import ABC
class Visitor(ABC):

  def visit_Statement(self, statement):
    pass

  def visit_ExprStmt(self, exprstmt):
    pass

  def visit_PrintStmt(self, printstmt):
    pass

  def visit_Var(self, var):
    pass

  def visit_Block(self, block):
    pass

# GENERATED BY syntax.py
class Statement:
  def __init__(self, stmt):
    self.stmt = stmt


  def accept(self, visitor):
    pass


# GENERATED BY syntax.py
class ExprStmt(Statement):
  def __init__(self, expr):
    super().__init__(self)
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_ExprStmt(self)


# GENERATED BY syntax.py
class PrintStmt(Statement):
  def __init__(self, expr):
    super().__init__(self)
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_PrintStmt(self)


# GENERATED BY syntax.py
class Var(Statement):
  def __init__(self, name, initializer):
    super().__init__(self)
    self.name = name
    self.initializer = initializer


  def accept(self, visitor):
    return visitor.visit_Var(self)


# GENERATED BY syntax.py
class Block(Statement):
  def __init__(self, lst_statements):
    super().__init__(self)
    self.lst_statements = lst_statements


  def accept(self, visitor):
    return visitor.visit_Block(self)

