
from abc import ABC
class Visitor(ABC):

  def visit_Statement(self, statement):
    pass

  def visit_ExprStmt(self, exprstmt):
    pass

  def visit_PrintStmt(self, printstmt):
    pass

  def visit_Var(self, var):
    pass

  def visit_Block(self, block):
    pass

  def visit_IfStmt(self, ifstmt):
    pass

  def visit_WhileStmt(self, whilestmt):
    pass

  def visit_Function(self, function):
    pass

  def visit_ReturnStmt(self, returnstmt):
    pass

  def visit_ClassStmt(self, classstmt):
    pass

# GENERATED BY syntax.py
class Statement:
  def __init__(self, stmt):
    self.stmt = stmt


  def accept(self, visitor):
    pass


# GENERATED BY syntax.py
class ExprStmt(Statement):
  def __init__(self, expr):
    super().__init__(self)
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_ExprStmt(self)


# GENERATED BY syntax.py
class PrintStmt(Statement):
  def __init__(self, expr):
    super().__init__(self)
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_PrintStmt(self)


# GENERATED BY syntax.py
class Var(Statement):
  def __init__(self, name, initializer):
    super().__init__(self)
    self.name = name
    self.initializer = initializer


  def accept(self, visitor):
    return visitor.visit_Var(self)


# GENERATED BY syntax.py
class Block(Statement):
  def __init__(self, lst_statements):
    super().__init__(self)
    self.lst_statements = lst_statements


  def accept(self, visitor):
    return visitor.visit_Block(self)


# GENERATED BY syntax.py
class IfStmt(Statement):
  def __init__(self, condition, then, else_):
    super().__init__(self)
    self.condition = condition
    self.then = then
    self.else_ = else_


  def accept(self, visitor):
    return visitor.visit_IfStmt(self)


# GENERATED BY syntax.py
class WhileStmt(Statement):
  def __init__(self, condition, body):
    super().__init__(self)
    self.condition = condition
    self.body = body


  def accept(self, visitor):
    return visitor.visit_WhileStmt(self)


# GENERATED BY syntax.py
class Function(Statement):
  def __init__(self, name, parameters, body):
    super().__init__(self)
    self.name = name
    self.parameters = parameters
    self.body = body


  def accept(self, visitor):
    return visitor.visit_Function(self)


# GENERATED BY syntax.py
class ReturnStmt(Statement):
  def __init__(self, return_token, value):
    super().__init__(self)
    self.return_token = return_token
    self.value = value


  def accept(self, visitor):
    return visitor.visit_ReturnStmt(self)


# GENERATED BY syntax.py
class ClassStmt(Statement):
  def __init__(self, name, methods):
    super().__init__(self)
    self.name = name
    self.methods = methods


  def accept(self, visitor):
    return visitor.visit_ClassStmt(self)

