
from abc import ABC
class Visitor(ABC):
  def visit(visitor):
    pass

# GENERATED BY syntax.py
class Expression:
  def __init__(self, expr):
    self.expr = expr


  def accept(self, visitor):
    pass


# GENERATED BY syntax.py
class Binary(Expression):
  def __init__(self, left_expr, op, right_expr):
    super().__init__(self)
    self.left_expr = left_expr
    self.op = op
    self.right_expr = right_expr


  def accept(self, visitor):
    return visitor.visit_Binary(self)


# GENERATED BY syntax.py
class Unary(Expression):
  def __init__(self, op, expr):
    super().__init__(self)
    self.op = op
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_Unary(self)


# GENERATED BY syntax.py
class Literal(Expression):
  def __init__(self, token):
    super().__init__(self)
    self.token = token


  def accept(self, visitor):
    return visitor.visit_Literal(self)


# GENERATED BY syntax.py
class Grouping(Expression):
  def __init__(self, expr):
    super().__init__(self)
    self.expr = expr


  def accept(self, visitor):
    return visitor.visit_Grouping(self)

