def get_visitor_string(syntax_class, class_types):
  formatted = """
from abc import ABC
class Visitor(ABC):
"""
  for name, parameters in class_types:
    formatted += f"""
  def visit_{name}(self, {name.lower()}):
    pass
"""
  return formatted
def get_formatted_string(syntax_class, class_types):
  formatted = get_visitor_string(syntax_class, class_types)
  for expr_type in class_types:
    name, parameters = expr_type
    formatted += f"""
# GENERATED BY syntax.py
class {name}{f"({syntax_class})" if name != syntax_class else ""}:
  def __init__(self, {", ".join(parameters)}):
    {"super().__init__(self)\n    " if name != syntax_class else ""}{"".join([f"self.{parameter} = {parameter}\n" + ("    " if i < len(parameters) - 1 else "") for i, parameter in enumerate(parameters)])}
{f"""
  def accept(self, visitor):
    {f"return visitor.visit_{name}(self)" if name != syntax_class else "pass"}
"""}
"""
  return formatted
def generate_ast_classes():
  expression_types = [
    ["Expression", ["expr"]],
    ["Assignment", ["name", "value"]],
    ["Binary", ["left_expr", "op", "right_expr"]],
    ["Unary", ["op", "expr"]],
    ["Literal", ["token"]],
    ["Grouping", ["expr"]],
    ["Variable", ["name"]],
    ["Logical", ["left_expr", "op", "right_expr"]],
    ["Call", ["callee", "closing_paren", "arguments"]]
  ]
  formatted_for_expression = get_formatted_string("Expression", expression_types)
  with open(f"expression_syntax_types.py", "w+") as f:
    f.write(formatted_for_expression)

  statement_types = [
    ["Statement", ["stmt"]],
    ["ExprStmt", ["expr"]],
    ["PrintStmt", ["expr"]],
    ["Var", ["name", "initializer"]],
    ["Block", ["lst_statements"]],
    ["IfStmt", ["condition", "then", "else_"]],
    ["WhileStmt", ["condition", "body"]],
    ["Function", ["name", "parameters", "body"]]
  ]
  formatted_for_statement = get_formatted_string("Statement", statement_types)
  with open(f"statement_syntax_types.py", "w+") as f:
    f.write(formatted_for_statement)

if __name__ == "__main__":
  generate_ast_classes()
