def generate_ast_classes():
  expression_types = [
    ["Expression", ["expr"]],
    ["Binary", ["left_expr", "op", "right_expr"]],
    ["Unary", ["op", "expr"]],
    ["Literal", ["token"]],
    ["Grouping", ["expr"]],
  ]
  formatted = """
from abc import ABC
class Visitor(ABC):
  def visit(visitor):
    pass
"""
  for expr_type in expression_types:
    name, parameters = expr_type
    formatted += f"""
# GENERATED BY syntax.py
class {name}{"(Expression)" if name != "Expression" else ""}:
  def __init__(self, {"".join([(s + ", " if i < len(parameters) - 1 else s) for i, s in enumerate(parameters)])}):
    {"super().__init__(self)\n    " if name != "Expression" else ""}{"".join([f"self.{parameter} = {parameter}\n" + ("    " if i < len(parameters) - 1 else "") for i, parameter in enumerate(parameters)])}
{f"""
  def accept(self, visitor):
    {f"return visitor.visit_{name}(self)" if name != "Expression" else "pass"}
"""}
"""
  with open(f"syntax_types.py", "w+") as f:
    f.write(formatted)

if __name__ == "__main__":
  generate_ast_classes()
